### ISSUE TITLE
Validate entities on import

### ISSUE THREAD

**Issue by mstenta** [pcambra/csv_importer#10]
Things to validate:

- Required fields
- Allowed values
- ... (more?)

**Comment by pcambra** [comment]
@mstenta as long as the validation is on the entity side, migrate now takes care of it after https://github.com/pcambra/csv_importer/commit/6efd4ed46b708375bc6a64edafd2c061a4d271c3

If the validation is on the form side such as allowed values, we need to enforce it in the way select or other is doing: https://git.drupalcode.org/project/select_or_other/-/blob/8.x-1.x/src/Plugin/Validation/AllowedValuesConstraintValidator.php#L89

**Comment by mstenta** [comment]
Makes sense! I'll open an upstream issue in farmOS about adding our own "allowed values" constraint.

**Comment by mstenta** [comment]
Ah and I suppose also one for required fields? Is that on the form level or the entity level, do you know?

**Comment by mstenta** [comment]
https://www.drupal.org/project/farm/issues/3227561

**Comment by pcambra** [comment]
Validation is executed correctly, required fields marked at the base field definition should trigger validation and with the issue above we can force it on all fields we need.

Closing this
